version: '3'

services:
 node:
   image: 'node:latest'
   user: 'node'
   working_dir: /home/node/app
   ports:
    - "3000:3000"
   environment:
    - NODE_ENV=production
   volumes:
    - ./:/home/node/app
   command: "npm start"
   links:
    - "mongo"
    - "mailtrap"
 mongo:
  image: mongo
  ports:
    - "27017:27017"
 mailtrap:
   image: 'eaudeweb/mailtrap'
   ports:
    - '8081:80'
volumes:
 mongodb_data_container: