version: '3'

services:
 node:
   image: 'node:latest'
   user: 'node'
   working_dir: /home/node/app
   expose:
    - "8082"
   environment:
    - NODE_ENV=production
   volumes:
    - ./:/home/node/app
   command: "npm start"
   links:
    - "mongo"
    - "mailtrap"
 mongo:
  image: mongo
  restart: always
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: example
 mailtrap:
   image: 'eaudeweb/mailtrap'
   ports:
    - '8081:80'
volumes:
 mysql-data: